#!/usr/bin/env bash
# A script that displays processes containing the bash word
#Requirements:
#    Must show all processes, for all users, including those which might not have a TTY
#    Display in a user-oriented format
#    Show process hierarchy

ps -auxf | grep bash
