#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process.
# Requirements:
#    You must use kill

TARGET=$(pgrep "bash.*infinity.*" -f | head -n 1)

if [[ -n $TARGET ]]; then
	kill "$TARGET"
fi
