#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
FILE=/etc/passwd
while read -r p
do
	echo "$p" | cut -d: -f1 | tr -d '\n'
	echo -n :
	echo "$p" | cut -d: -f3 | tr -d '\n'
	echo -n :
	echo "$p" | cut -d: -f6
done <$FILE
