#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=0
LIMIT=10
text="Best School"

while [ $i -lt $LIMIT ]
do
	echo "$text"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	i=$((i+1))
done
