#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#    display hours from 0 to 12
#    display minutes from 1 to 59

hrs=12
mins=60
i=0

while [ $i -le "$hrs" ]
do
	j=1
	echo "Hours: $i"

	while [ $j -lt "$mins" ]
	do
		echo "$j"
		j=$((j + 1))
	done
	i=$((i + 1))
done
