#!/usr/bin/env bash
# A Bash script that gives you information about the school file

my_file=school

if [ -e $my_file ] ; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 1
fi

if [ -s $my_file ] ; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ -f $my_file ] ; then
	echo "school is a regular file"
fi
