#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

file_path="/etc/hosts"

$(cp "$file_path" ./old)
sed -i '0,/127\.0\.0\.1.*localhost/s//127.0.0.2\tlocalhost/' "$file_path"
sed -i 's/.*facebook.*//g' "$file_path"
echo -e "\n8.8.8.8 \tfacebook.com" >>"$file_path"
