#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

file_path="/etc/hosts"

sed -i '0,/127\.0\.0\.1/s//127.0.0.2/' "$file_path"
echo -e "8.8.8.8\tfacebook.com" >>"$file_path"
